### ISSUE TITLE
limit virtual interfaces to specific engines

### ISSUE THREAD

**Issue by micah** [searx/searx#1028]
Because so many people have problems with google blocking results due to a single IP making many queries (see #729), it seems the only way to get around this is to have a pool of IPs that can be used to make queries, spreading the load around. 

This can be done by setting the outgoing interfaces in virtual interfaces in https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L43, it works fine if you have an excess of IPv4 addresses to spare for this purpose. However, most people do not have spare IPv4. Many people do have large numbers of ipv6 addresses, but if you configure several virtual interfaces to use ipv6 addresses, then the engines that do not support ipv6 will fail.

It would be good if there were a possibility to configure which engines are used in virtual interfaces, so you can configure a bunch of ipv6 virtual interfaces, but only limit them to those engines that support ipv6.

**Comment by dalf** [comment]
Technical informations :
* https://github.com/requests/requests/issues/1691
* https://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6

**Comment by misnyo** [comment]
I'll take a look on this soon.

**Comment by xinomilo** [comment]
startpage, bing, reddit and others, aren't accessible to ipv6. no AAAA records.  in ipv6 vm, most engines produce same error.
wikidata is working here in a test ipv6 instance, so don't know why the exception there. what does uwsgi say?

**Comment by micah** [comment]
xinomilo <notifications@github.com> writes:

> startpage, bing, reddit and others, aren't accessible to ipv6. no AAAA
> records.  in ipv6 vm, most engines produce same error.

Same with duckduckgo, no AAAA records.

> wikidata is working here in a test ipv6 instance, so don't know why the exception there. what does uwsgi say? 

```
ERROR:searx.search:engine wikidata : requests exception(search duration : 0.77158498764 s, timeout: 3.0 s) : HTTPSConnectionPool(host='www.wikidata.org', port=443): Max retries exceeded with url: /w/api.php?action=parse&format=json&page=Q10443&uselang=en&redirects=1&prop=text%7Cdisplaytitle%7Clanglinks%7Crevid&disableeditsection=1&disabletidy=1&preview=1&sectionpreview=1&disabletoc=1&utf8=1&formatversion=2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b9dfe6ad0>: Failed to establish a new connection: [Errno -9] Address family for hostname not supported',))
Traceback (most recent call last):
  File "/srv/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/srv/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/srv/searx/searx/engines/wikidata.py", line 80, in response
    htmlresponse = get(url)
  File "/srv/searx/searx/poolrequests.py", line 133, in get
    return request('get', url, **kwargs)
  File "/srv/searx/searx/poolrequests.py", line 109, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/srv/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/srv/searx/searx-ve/local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='www.wikidata.org', port=443): Max retries exceeded with url: /w/api.php?action=parse&format=json&page=Q10443&uselang=en&redirects=1&prop=text%7Cdisplaytitle%7Clanglinks%7Crevid&disableeditsection=1&disabletidy=1&preview=1&sectionpreview=1&disabletoc=1&utf8=1&formatversion=2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b9dfe6ad0>: Failed to establish a new connection: [Errno -9] Address family for hostname not supported',))
Exception in thread 8075e2f3-96dc-4eac-afd8-06a2038f1345:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/srv/searx/searx/search.py", line 150, in search_one_request_safe
    engine.suspend_end_time = time() + min(settings['search']['max_ban_time_on_fail'],
NameError: global name 'settings' is not defined
```

that looks like there is no AAAA record for www.wikidata.org either, but
it does have one:

```
$host www.wikidata.org
www.wikidata.org has address 208.80.154.224
www.wikidata.org has IPv6 address 2620:0:861:ed1a::1
```

**Comment by xinomilo** [comment]
usually you get "[Errno 101] Network is unreachable" for engines without AAAA / ipv6.
this error "[Errno -9] Address family for hostname not supported" could indicate something else wrong with ipv6. 
local setttings maybe(?) is everything else working ok in that host with ipv6? dns lookups?
