### ISSUE TITLE
KeyError: 'doi_resolvers'

### ISSUE THREAD

**Issue by gitbugged** [searx/searx#1103]
Since most recent pull by @kvch, I am unable to run Searx from git.

https://github.com/asciimoo/searx/commit/1b10abfc92afed36627c7052b89d2de5e7f537ee
Traceback (most recent call last):
  File "/usr/local/searx/searx/webapp.py", line 65, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
  File "/usr/local/searx/searx/search.py", line 34, in <module>
    from searx.plugins import plugins
  File "/usr/local/searx/searx/plugins/__init__.py", line 25, in <module>
    from searx.plugins import (oa_doi_rewrite,
  File "/usr/local/searx/searx/plugins/oa_doi_rewrite.py", line 14, in <module>
    doi_resolvers = settings['doi_resolvers']
KeyError: 'doi_resolvers'

**Comment by asciimoo** [comment]
@gitbugged do you have "doi_resolvers" section in your settings.yml (https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L741) ?

**Comment by gitbugged** [comment]
@asciimoo, for some reason it was missing. Pulling latest git fixed the issue - thank you!
