### ISSUE TITLE
Server error when accessing the css and js files

### ISSUE THREAD

**Issue by Venca24** [searx/searx#1179]
I tried to run searx on my localhost just for testing. I've installed it according to [the manual](https://asciimoo.github.io/searx/dev/install/installation.html) from the actual master branch only without creating separate user and I'm alway getting this error:

INFO:werkzeug:127.0.0.1 - - [07/Feb/2018 22:49:16] "GET /static/plugins/js/search_on_category_select.js HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/venca/programování/py/searx/searx/webapp.py", line 910, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 928, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 669, in send_from_directory
    filename = safe_join(directory, filename)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 639, in safe_join
    return posixpath.join(*parts)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)

The main page and result pages  are appearing normally, it "just" doesn't have access to the style and js files. I'm running it on Kubuntu 16.04 with python 2.7.12.

**Comment by Venca24** [comment]
It is because of diacritics in the name of one folder in the absolute path in the computer.
