### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by dalf** [searx/searx#1230]
I've tried [Gandi simple hosting](https://www.gandi.net/en/simple-hosting) (searx.space), it works but there are a lot of ECONNRESET errors :
```
ERROR:searx.search:engine wikipedia : requests exception(search duration : 0.0280680656433 s, timeout: 5.0 s) : ('Connection aborted.', error("(104, 'ECONNRESET')",))
Traceback (most recent call last):
  File "./searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "./searx/search.py", line 83, in search_one_request
    response = send_http_request(engine, request_params)
  File "./searx/search.py", line 67, in send_http_request
    return req(request_params['url'], **request_args)
  File "./searx/poolrequests.py", line 133, in get
    return request('get', url, **kwargs)
  File "./searx/poolrequests.py", line 109, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))
```

[EDIT] I guess the Gandi architecture cuts the HTTP connections.

According to https://github.com/requests/requests/issues/3845#issuecomment-276897354 one way to fix is : 
```python
import requests
from requests.adapters import HTTPAdapter

s = requests.Session()
s.mount('http', HTTPAdapter(max_retries=3))
s.mount('https', HTTPAdapter(max_retries=3))
```

[EDIT] Another way is to disable persistent connections.

----

Side note : the wsgi.py requires by Gandi : 
```python
import searx.webapp
application = searx.webapp.app
```

**Comment by unixfox** [comment]
Did Gandi changed their simple hosting solution since you created this issue @dalf? Are you still able to reproduce that error on their platform?

**Comment by dalf** [comment]
I don't use Gandi hosting anymore.
