### ISSUE TITLE
Trying to access /config throws an HTTP 500 error.

### ISSUE THREAD

**Issue by virtadpt** [searx/searx#1245]
Some code I wrote which uses the Searx search API tries to access /config when it starts up to figure out which search engines are configured on my instance.  I updated earlier tonight (commit b8543bcf3a4cc176645473165fcc855ae3a8210c) and when I try to hit that URI with my code or with CURL, Searx throws an error 500.

Arch Linux, 20180317 (64-bit).
Python: v2.7.14
Followed installation instructions: Yes.

Stack trace:
```
(env) [searx@leandra searx]$ python searx/webapp.py
[2018-03-17 00:40:52,268] ERROR in app: Exception on /config [GET]
Traceback (most recent call last):
  File "/opt/searx/searx/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/searx/searx/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/searx/searx/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/searx/searx/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/searx/searx/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "searx/webapp.py", line 858, in config
    'doi_resolvers': [r for r in search['doi_resolvers']],
NameError: global name 'search' is not defined
```
I've blown away my Searx install and reinstalled from scratch, using only the installation instructions (no customizations to searx/config.yml) and the same thing happens.

I'm not sure what's going on here - has this been reported yet?  Is there anything else I can provide?

**Comment by asciimoo** [comment]
@virtadpt thanks for the report, hopefully it is fixed in  b9d4c05 .

**Comment by virtadpt** [comment]
Thanks - I'll give it a try today.

**Comment by virtadpt** [comment]
That appears to have been it - thank you!
