### ISSUE TITLE
Error when searching using a specific engine 

### ISSUE THREAD

**Issue by dalf** [searx/searx#1253]
Whatever the engine( [example](https://searx.me/?q=%21google+test&language=en-US&time_range=&category_general=on&safesearch=0&theme=simple) ), there is an error using the last revision of searx : 
```
ERROR:searx.webapp:search error
Traceback (most recent call last):
  File "searx/webapp.py", line 489, in index
    search_query = get_search_query_from_webapp(request.preferences, request.form)
  File "/home/alexandre/code/searx/nclean/searx/searx/search.py", line 202, in get_search_query_from_webapp
    raw_text_query.parse_query()
  File "/home/alexandre/code/searx/nclean/searx/searx/query.py", line 121, in parse_query
    for engine_category in engines[engine_name].categories:
UnboundLocalError: local variable 'engine_name' referenced before assignment
```

**Comment by asciimoo** [comment]
Thanks for the report!

**Comment by dalf** [comment]
szívesen
(I've searched :-) )
