### ISSUE TITLE
Google Captha--on MAC

### ISSUE THREAD

**Issue by ghost** [searx/searx#1431]
```
ERROR:searx.search:engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/Users/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/Users/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/Users/searx/searx/engines/google.py", line 213, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required
ERROR:searx.search:engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/Users/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/Users/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/Users/searx/searx/engines/google.py", line 213, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required
ERROR:searx.search:engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/Users/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/Users/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/Users/searx/searx/engines/google.py", line 213, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required
WARNING:searx.search:engine timeout: piratebay
ERROR:searx.search:engine piratebay : HTTP requests timeout(search duration : 3.312645196914673 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.search:engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/Users/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/Users/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/Users/searx/searx/engines/google.py", line 213, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required
ERROR:searx.search:engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/Users/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/Users/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/Users/searx/searx/engines/google.py", line 213, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required
WARNING:searx.search:engine timeout: wikipedia
WARNING:searx.search:engine timeout: bing
WARNING:searx.search:engine timeout: wikidata
ERROR:searx.search:engine wikidata : HTTP requests timeout(search duration : 5.517826795578003 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.search:engine wikipedia : HTTP requests timeout(search duration : 6.383588790893555 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine bing : HTTP requests timeout(search duration : 9.439538717269897 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/Users/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/Users/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/Users/searx/searx/engines/google.py", line 213, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required
WARNING:searx.search:engine timeout: piratebay
ERROR:searx.search:engine piratebay : HTTP requests timeout(search duration : 4.311842679977417 s, timeout: 3.0 s) : ReadTimeout
WARNING:searx.search:engine timeout: deviantart
WARNING:searx.search:engine timeout: flickr
WARNING:searx.search:engine timeout: google images
WARNING:searx.search:engine timeout: qwant images
ERROR:searx.search:engine google images : HTTP requests timeout(search duration : 3.0330801010131836 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.search:engine qwant images : HTTP requests timeout(search duration : 3.74033784866333 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/Users/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/Users/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/Users/searx/searx/engines/google.py", line 213, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required
WARNING:searx.search:engine timeout: bing
ERROR:searx.search:engine bing : HTTP requests timeout(search duration : 3.191767692565918 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.search:engine flickr : HTTP requests timeout(search duration : 4.396630048751831 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.search:engine deviantart : HTTP requests timeout(search duration : 6.915150165557861 s, timeout: 3.0 s) : ReadTimeout
WARNING:searx.search:engine timeout: wikipedia
WARNING:searx.search:engine timeout: wikidata
WARNING:searx.search:engine timeout: google
ERROR:searx.search:engine wikipedia : HTTP requests timeout(search duration : 3.0552639961242676 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.search:engine google : HTTP requests timeout(search duration : 3.058770179748535 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.search:engine wikidata : HTTP requests timeout(search duration : 3.0949208736419678 s, timeout: 3.0 s) : ReadTimeout
ERROR:searx.webapp:search error
Traceback (most recent call last):
  File "webapp.py", line 491, in index
    search_query = get_search_query_from_webapp(request.preferences, request.form)
  File "/Users/searx/searx/search.py", line 195, in get_search_query_from_webapp
    raise SearxParameterException('q', '')
searx.exceptions.SearxParameterException: Empty q parameter
ERROR:flask.app:Exception on / [POST]
Traceback (most recent call last):
  File "webapp.py", line 491, in index
    search_query = get_search_query_from_webapp(request.preferences, request.form)
  File "/Users/searx/searx/search.py", line 195, in get_search_query_from_webapp
    raise SearxParameterException('q', '')
searx.exceptions.SearxParameterException: Empty q parameter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "webapp.py", line 501, in index
    return index_error(output_format, e.message), 400
AttributeError: 'SearxParameterException' object has no attribute 'message'
```

**Comment by Pofilo** [comment]
There is a search bar in the issues section, you should search first before creating a 20th duplicate ;)

**Comment by dalf** [comment]
See #729
