### ISSUE TITLE
wolframalpha engine is broken

### ISSUE THREAD

**Issue by rnhmjoj** [searx/searx#1480]
The wolframalpha engine appears to be broken in 0.15.0
```
searx-run[9330]: ERROR:searx.search:engine wolframalpha : exception : Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
searx-run[9330]: Traceback (most recent call last):
searx-run[9330]:   File "/nix/store/rf8v47ispmh7bp0rbl291ml1fivfs424-searx-0.15.0/lib/python3.6/site-packages/searx/search.py", line 104, in search_one_request_safe
searx-run[9330]:     search_results = search_one_request(engine, query, request_params)
searx-run[9330]:   File "/nix/store/rf8v47ispmh7bp0rbl291ml1fivfs424-searx-0.15.0/lib/python3.6/site-packages/searx/search.py", line 87, in search_one_request
searx-run[9330]:     return engine.response(response)
searx-run[9330]:   File "/nix/store/rf8v47ispmh7bp0rbl291ml1fivfs424-searx-0.15.0/lib/python3.6/site-packages/searx/engines/wolframalpha_api.py", line 68, in response
searx-run[9330]:     search_results = etree.XML(resp.text)
searx-run[9330]:   File "src/lxml/etree.pyx", line 3192, in lxml.etree.XML
searx-run[9330]:   File "src/lxml/parser.pxi", line 1872, in lxml.etree._parseMemoryDocument
searx-run[9330]: ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by kvch** [comment]
Could you please share an example search query which leads to this exception? I have failed to come up with one.

**Comment by rnhmjoj** [comment]
I have configured searx to use the `wolframalpha_api` engine with a valid api key (I tested it with curl). Enabling the science category any query results in this error.

**Comment by rnhmjoj** [comment]
Thank you!
