### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by 1265775896** [searx/searx#1499]
Happens when I go to preferences
It shows
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
And it works if I change the default theme, 
But after I changed it back to default, it happened again, and my changes of theme doesn't work anymore(I Checked that nothing wrong and Restarted)
Debug shows these:
```
builtins.TypeError
TypeError: float() argument must be a string or a number, not 'dict'

Traceback (most recent call last)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/root/searx/searx/webapp.py", line 929, in __call__
return self.app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
return self.app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/root/searx/searx/webapp.py", line 725, in preferences
preferences=True)
File "/root/searx/searx/webapp.py", line 400, in render
'{}/{}'.format(kwargs['theme'], template_name), **kwargs)
File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
context, ctx.app)
File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
rv = template.render(context)
File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
return original_render(self, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/root/searx/searx/templates/oscar/preferences.html", line 2, in top-level template code
{% extends "oscar/base.html" %}
File "/root/searx/searx/templates/oscar/base.html", line 82, in top-level template code
{% block content %}
File "/root/searx/searx/templates/oscar/preferences.html", line 78, in block "content"
{% set method_info = _('Change how forms are submited, <a href="http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods" rel="external">learn more about request methods</a>') %}
File "/usr/local/lib/python3.6/site-packages/jinja2/ext.py", line 134, in _gettext_alias
return __context.call(__context.resolve('gettext'), *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/jinja2/ext.py", line 143, in gettext
return rv % variables
File "/usr/local/lib/python3.6/site-packages/markupsafe/__init__.py", line 102, in __mod__
return self.__class__(text_type.__mod__(self, arg))
File "/usr/local/lib/python3.6/site-packages/markupsafe/__init__.py", line 315, in __float__
return float(self.obj)
TypeError: float() argument must be a string or a number, not 'dict'
```
And other functions works fine.
I'm really confused now, help plz!

System: CentOS 7
python2.7 and python3.6 both tried and got same error

**Comment by EdisonJwa** [comment]
I was got the same error on Ubuntu 18.04 and Debian 9
python 3.6 and 3.7

**Comment by ppss1806** [comment]
Through many attempts, I found that this problem comes from the Chinese selected by "Interface language".
My temporary solution is to change the "default_locale" value of the “settings.yml” to be non-Chinese.

**Comment by 1265775896** [comment]
> Through many attempts, I found that this problem comes from the Chinese selected by "Interface language".
> My temporary solution is to change the "default_locale" value of the “settings.yml” to be non-Chinese.

It works! Thank you so much!
