### ISSUE TITLE
TypeError: float() argument must be a string or a number

### ISSUE THREAD

**Issue by colddaytk** [searx/searx#1520]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/searx/searx/webapp.py", line 929, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/searx/searx/webapp.py", line 725, in preferences
    preferences=True)
  File "/usr/local/searx/searx/webapp.py", line 400, in render
    '{}/{}'.format(kwargs['theme'], template_name), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx/templates/oscar/preferences.html", line 2, in top-level template code
    {% extends "oscar/base.html" %}
  File "/usr/local/searx/searx/templates/oscar/base.html", line 82, in top-level template code
    {% block content %}
  File "/usr/local/searx/searx/templates/oscar/preferences.html", line 78, in block "content"
    {% set method_info = _('Change how forms are submited, <a href="http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods" rel="external">learn more about request methods</a>') %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/ext.py", line 143, in gettext
    return rv % variables
  File "/usr/local/lib/python2.7/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python2.7/dist-packages/markupsafe/__init__.py", line 315, in __float__
    return float(self.obj)
TypeError: float() argument must be a string or a number

**Comment by jfowl** [comment]
Hi!

What action did you perform to produce this error?
What version of searx were you running at that time?

**Comment by colddaytk** [comment]
Oh,I am sorry to have delayed your coffee time.It may be a firefox problem,when I use Chrome or EDGE,there is no problem.

**Comment by colddaytk** [comment]
my searx is 0.15.0,when I click preference in firefox this problem will appear,but there is no problem when I use chrome or EDGE.
