### ISSUE TITLE
Exception when you search for an empty string

### ISSUE THREAD

**Issue by fgossel** [searx/searx#1722]
Hi, 

 it seems like there is an incorrect (or at least weird) behaviour when you "search" for an empty string from the Searx page. This leads to Internal Server Error. In uWSGI error log I can see this exception:

`
Traceback (most recent call last):
  File "/opt/searx/venv3/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/searx/venv3/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/searx/venv3/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/searx/venv3/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/searx/venv3/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/searx/venv3/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/searx/searx/webapp.py", line 520, in index
    return index_error(output_format, e.message), 400
AttributeError: 'SearxParameterException' object has no attribute 'message'
`

Empty searching from the FF search bar seems to be correct. I tested it on other instances as well and the result is the same.

**Comment by fgossel** [comment]
Thanks for your quick fix. This only corrects exception behavior. Now it looks much better. 
But my point was empty search parameter should not be considered as an error as it shows in the log file. 

`
ERROR:searx.webapp:search error
Traceback (most recent call last):
  File "/opt/searx/searx/webapp.py", line 510, in index
    search_query, raw_text_query = get_search_query_from_webapp(request.preferences, request.form)
  File "/opt/searx/searx/search.py", line 221, in get_search_query_from_webapp
    raise SearxParameterException('q', '')
searx.exceptions.SearxParameterException: Empty q parameter
`
