### ISSUE TITLE
Crash on OpenBSD 6.6

### ISSUE THREAD

**Issue by ghost** [searx/searx#1727]
OS: OpenBSD 6.6 amd64
Python Version: 3.7.4
Branch: master
```
$ python3 searx/webapp.py
searx/webapp.py:969: DeprecationWarning: 'werkzeug.contrib.fixers.ProxyFix' has moved to 'werkzeug.middleware.proxy_fix.ProxyFix'. This import is deprecated as of version 0.15 and will be removed in 1.0.
  app.wsgi_app = ReverseProxyPathFix(ProxyFix(application.wsgi_app))
 * Serving Flask app "webapp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/www/searx/searx/engines/__init__.py", line 261, in engine_init
    init_fn(get_engine_from_settings(engine_name))
  File "/home/www/searx/searx/engines/soundcloud.py", line 72, in init
    guest_client_id = get_client_id()
  File "/home/www/searx/searx/engines/soundcloud.py", line 50, in get_client_id
    response = http_get("https://soundcloud.com")
  File "/home/www/searx/searx/poolrequests.py", line 133, in get
    return request('get', url, **kwargs)
  File "/home/www/searx/searx/poolrequests.py", line 109, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 286, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 438, in verify_mode
    self._ctx.set_verify(_stdlib_to_openssl_verify[value], _verify_callback)
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1103, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/home/www/searx/searx-ve/lib/python3.7/site-packages/OpenSSL/SSL.py", line 333, in __init__
    "int (*)(int, X509_STORE_CTX *)", wrapper)
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```
![2019-10-22_16-41](https://user-images.githubusercontent.com/56886463/67309974-8cf4b600-f505-11e9-8d1d-398d8b9bb1f2.png)

**Comment by ghost** [comment]
Works after installing in /usr/local.

**Comment by CadeOlsen** [comment]
Did you have success trying to use it with uWSGI and httpd? I am also getting this same error even installing in /usr/local.
