### ISSUE TITLE
yahoo unexpected crash

### ISSUE THREAD

**Issue by Perflyst** [searx/searx#1733]
Is this a block by Yahoo? I can access Yahoo still via curl

```
ERROR:searx.search:engine yahoo : exception : line 22: ID top already defined (line 22)
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/usr/local/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/usr/local/searx/searx/engines/yahoo.py", line 100, in response
    dom = html.fromstring(resp.text)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 876, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 762, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1758, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 649, in lxml.etree._raiseParseError
XMLSyntaxError: line 22: ID top already defined (line 22)
```

**Comment by Perflyst** [comment]
```
# curl https://de.search.yahoo.com/search?p=test -I
HTTP/2 500
```

Interesting, they are returning a 500 error for me if I do a search.

**Comment by asciimoo** [comment]
It works for me. If you have further information, feel free to reopen.

**Comment by Perflyst** [comment]
I changed to master branch, looks like it is fixed there.
