### ISSUE TITLE
cannot import: "from sympy.parsing.sympy_parser import parse_expr"

### ISSUE THREAD

**Issue by pointhi** [searx/searx#187]
Currently I'm working on an CAS-System for searx. Something similar as http://gamma.sympy.org/, build with the same CAS-core, but optimised to be used inside searx.

I have installed sympy in searx using setup.py, requirements.txt and versions.cfg and then call `make minimal`

But If I import [`parse_expr`](http://docs.sympy.org/0.7.3/modules/parsing.html?highlight=parse_expr):

``` python
from sympy.parsing.sympy_parser import parse_expr
```

 the following error occour:

```
Traceback (most recent call last):
  File "bin/searx-run", line 26, in <module>
    import searx.webapp
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/webapp.py", line 45, in <module>
    from searx.engines import (
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/engines/__init__.py", line 209, in <module>
    engine = load_engine(engine_data)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/engines/__init__.py", line 51, in load_engine
    engine = load_module(engine_name + '.py')
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/engines/__init__.py", line 44, in load_module
    module = load_source(modname, filepath)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/engines/sympy.py", line 10, in <module>
    from sympy.parsing.sympy_parser import parse_expr
ImportError: No module named parsing.sympy_parser
```

inside the python-shell, the line is working correctly. I didn't found anything which could cause that error. So I would ask, what could be the problem for this error?

thx, pointhi

**Comment by asciimoo** [comment]
That's strange, i have no clue.. Maybe wrong pythonpath?

**Comment by Cqoicebordel** [comment]
I thinked more of a python version issue, but honestly, no clue either...

**Comment by pointhi** [comment]
the line `from sympy.parsing.sympy_parser import parse_expr` is working as well in the `python2` and the `python2.7` shell.

Inside the `python3.4` shell the error `ImportError: No module named 'sympy'` is thrown, but thats probably because `make minimal` make a python 2.7 installation.

Furhermore, there is one more curiosity:

if I'm adding the same line `from sympy.parsing.sympy_parser import parse_expr` additionaly to webapp.py, no ImportError is thrown. But If I'm calling the methode `parse_expr` inside the engine, the following error is thrown:

```
Traceback (most recent call last):
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/search.py", line 42, in search_request_wrapper
    return fn(url, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/eggs/requests-2.2.0-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/eggs/requests-2.2.0-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/eggs/requests-2.2.0-py2.7.egg/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/eggs/requests-2.2.0-py2.7.egg/requests/sessions.py", line 491, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/eggs/requests-2.2.0-py2.7.egg/requests/hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/search.py", line 102, in process_callback
    search_results = callback(response)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/engines/sympy.py", line 37, in response
    expr = parse_expr(query)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/eggs/sympy-0.7.6-py2.7.egg/sympy/parsing/sympy_parser.py", line 820, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/eggs/sympy-0.7.6-py2.7.egg/sympy/parsing/sympy_parser.py", line 733, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
NameError: name 'Integer' is not defined
```

The same if I call this function inside webapp.py

The package-index of https://pypi.python.org/pypi/sympy tell me that it is compatible with python 2.7 as well with python 3.4.

**Comment by asciimoo** [comment]
@pointhi is the same happen if you start the instance with the `python2 searx/webapp.py` command?

**Comment by pointhi** [comment]
It seems sympy is able to be included into a searx-plugin. Now I can start with the implementation of a math-plugin.
