### ISSUE TITLE
Werkzeug v1.0 removed 'contrib' package

### ISSUE THREAD

**Issue by return42** [searx/searx#1876]
python searx/webapp.py
     Traceback (most recent call last):
      File "searx/webapp.py", line 50, in <module>
         from werkzeug.contrib.fixers import ProxyFix
     ModuleNotFoundError: No module named 'werkzeug.contrib'

See https://github.com/pallets/werkzeug/issues/1714 FYI conversation has been locked and limited to collaborators

Fixing the import ...

```diff
diff --git a/searx/webapp.py b/searx/webapp.py
index 446c5404..ae2c5b97 100755
--- a/searx/webapp.py
+++ b/searx/webapp.py
@@ -47,7 +47,7 @@ except:
     from html import escape
 from datetime import datetime, timedelta
 from time import time
-from werkzeug.contrib.fixers import ProxyFix
+from werkzeug.middleware.proxy_fix import ProxyFix
 from flask import session
 from flask import (
     Flask, request, render_template, url_for, Response, make_response,
```

brings the next error from flask_babel

```
Traceback (most recent call last):
  File "searx/webapp.py", line 56, in <module>
    from flask_babel import Babel, gettext, format_date, format_decimal
  File "/usr/local/searx/searx-pyenv/lib/python3.8/site-packages/flask_babel/__init__.py", line 19, in <module>
    from werkzeug import ImmutableDict
ImportError: cannot import name 'ImmutableDict' from 'werkzeug' (/usr/local/searx/searx-pyenv/lib/python3.8/site-packages/werkzeug/__init__.py)
```

**Comment by unixfox** [comment]
The import should already be fixed: https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L51
Related to this PR: https://github.com/asciimoo/searx/pull/1831 and this issue: https://github.com/asciimoo/searx/issues/1830

**Comment by return42** [comment]
Argh sorry .. forgot to update my branch :o
