### ISSUE TITLE
vimeo engine exception 'Expecting value: line 1 column 1 (char 0)'

### ISSUE THREAD

**Issue by nfk** [searx/searx#2081]
On my searx instance (searx 0.17.0) I have a lot of time this issue on production about vimeo engine.
Do you have any idea how I can debug or fix that one easily ? 

```
[2020-07-17 11:46:00 +0000] [7] [ERROR] engine vimeo : exception : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/searx/search.py", line 160, in search_one_http_request_safe
    search_results = search_one_http_request(engine, query, request_params)
  File "/usr/local/lib/python3.8/site-packages/searx/search.py", line 101, in search_one_http_request
    return engine.response(response)
  File "/usr/local/lib/python3.8/site-packages/searx/engines/vimeo.py", line 45, in response
    data = loads(resp.text[data_start_pos:data_end_pos])
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by return42** [comment]
> Do you have any idea how I can debug or fix that one easily ?

easily :) .. no sorry .. do you have python experience? debugging a multi threaded application (especial in production) isn't an easy task.

I tried to reproduce your issue with a local instance (using `make run`) but did not have luck.  Do you have some hints for me to reproduce this error .. e.g. is it reproducible with a special search term or is it more sporadic incident?

**Comment by unixfox** [comment]
I can't reproduce the bug when running a local Searx instance. Your IP may be banned by vimeo, and we can't do anything against that expect to use a proxy. Feel free to reopen this issue if you still experience the bug.

![image](https://user-images.githubusercontent.com/4016501/93883955-edc6d880-fcea-11ea-9c47-43f36687b2b9.png)
