### ISSUE TITLE
Firefox 81.1.1 on Android crashes searx when trying to add it as searchengine

### ISSUE THREAD

**Issue by bjo81** [searx/searx#2221]
Within the new Firefox for Android, it is possible to add search engines, but only for GET.
When I try to add `https://searx.mydomain.org/?q=%s`, Firefox creates a GET request with `/?q=1` leading to

```
ERROR:searx.webapp:Exception on / [GET]
 Traceback (most recent call last):
   File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispat>
     rv = self.handle_user_exception(e)
   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user>
     reraise(exc_type, exc_value, tb)
   File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
     raise value
   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispat>
     rv = self.dispatch_request()
   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_re>
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/usr/lib/python3.8/site-packages/searx/webapp.py", line 710, in index
     number_of_results=format_decimal(number_of_results),
   File "/usr/lib/python3.8/site-packages/flask_babel/__init__.py", line 458, in f>
     locale = get_locale()
   File "/usr/lib/python3.8/site-packages/flask_babel/__init__.py", line 226, in g>
     rv = babel.locale_selector_func()
   File "/usr/lib/python3.8/site-packages/searx/webapp.py", line 190, in get_locale
     locale = _get_browser_language(request, settings['locales'].keys())
   File "/usr/lib/python3.8/site-packages/searx/webapp.py", line 185, in _get_brow>
     return settings['search']['default_lang'] or 'en'
 KeyError: 'default_lang'
```
Setting a default_lang did not help. When I use `http://searx.mydomain.org/?q=%s` it works, maybe nginx adds something while redirecting it to https?

**Comment by 0xhtml** [comment]
Looks like searx is missing the setting `default_lang` in `settings.yml`. Could you verify that `default_lang` is set inside of `settings.yml` and post the corresponding lines (or the whole file)?

**Comment by bjo81** [comment]
Oops, I put `default_lang` into the wrong section, in `ui` instead of `search`. Now it works.
