### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'is_redirect'

### ISSUE THREAD

**Issue by pointhi** [searx/searx#253]
For a few repositories (my searx_oe5tpo and the metorology branche from @dalf), I get everytime the following error:

```
ERROR:searx.search:duckduckgo : engine exception : 'Response' object has no attribute 'is_redirect'
Traceback (most recent call last):
  File "/home/thomas/Dokumente/Projekte/searx/better_stats/searx/searx/search.py", line 67, in search_request_wrapper
    return fn(url, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/better_stats/searx/searx/poolrequests.py", line 35, in get
    return request('get', url, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/better_stats/searx/searx/poolrequests.py", line 28, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/better_stats/searx/eggs/requests-2.2.0-py2.7.egg/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/better_stats/searx/eggs/requests-2.2.0-py2.7.egg/requests/sessions.py", line 491, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/better_stats/searx/eggs/requests-2.2.0-py2.7.egg/requests/hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/thomas/Dokumente/Projekte/searx/better_stats/searx/searx/search.py", line 127, in process_callback
    if response.is_redirect is True:
AttributeError: 'Response' object has no attribute 'is_redirect'
WARNING:searx.search:startpage : engine timeout (waiting for threads)
```

**Comment by dalf** [comment]
I can't reproduce the bug.

Does it solve with :

``` python
if hasattr(response, 'is_redirect') and response.is_redirect is True: 
```

?

**Comment by pointhi** [comment]
yes, that line solve this issue.

**Comment by asciimoo** [comment]
Same as @dalf, i cannot reproduce it.
@pointhi what is the version of the `requests` lib?

**Comment by pointhi** [comment]
I think 2.2.0

edit: and there is also grequests 0.2.0

**Comment by asciimoo** [comment]
hmm.. strange..

(note: grequests is not part of searx anymore)

**Comment by pointhi** [comment]
The bug is occouring on my server, and on my local computer for some branches.

**Comment by Cqoicebordel** [comment]
Did you merge correctly the wrapper that handled redirect issue in the engines ?

**Comment by pointhi** [comment]
I have merged the current master into a branche, and now I get also the following error:

```
Traceback (most recent call last):
  File "bin/searx-run", line 25, in <module>
    import searx.webapp
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/webapp.py", line 40, in <module>
    from searx.poolrequests import get as http_get
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/poolrequests.py", line 48, in <module>
    http_adapters = cycle((HTTPAdapterWithConnParams(pool_connections=100), ))
  File "/home/thomas/Dokumente/Projekte/searx/searx_quick_fix/searx/searx/poolrequests.py", line 14, in __init__
    self.max_retries = requests.adapters.Retry(0, read=False)
AttributeError: 'module' object has no attribute 'Retry'
```

running

```
make clean
make minimal
```

doesn't solve this issue.

The same if I'm running that line with the python shell.

EDIT:

the error is also occouring, if I'm downloading the master branche and install it with `make minimal`.

**Comment by ghost** [comment]
I get the same error when using https://aur.archlinux.org/packages/searx-git/

**Comment by pointhi** [comment]
#257

**Comment by ghost** [comment]
I still have the same error, when i build from the AUR (last git version, so). Can anyone confirm ?

**Comment by pointhi** [comment]
The dependencies are wrong. You have to change them from `python2-grequests` to `python2-requests`, probably it is working afterwords.

**Comment by ghost** [comment]
Well, nope :|

```
[Hyperion]/home/reventlov/searx-git# LANG=C pacman -Qi searx-git                                                                                                                                               2015-03-02 20:14:18
Name           : searx-git
Version        : r1231.v0.7.076g9981725-1
Description    : A privacy-respecting, hackable metasearch engine
Architecture   : any
URL            : https://searx.0x2a.tk/
Licenses       : AGPL
Groups         : None
Provides       : None
Depends On     : python2-flask  python2-flask-babel  python2-requests  python2-lxml  python2-yaml  python2-dateutil
Optional Deps  : None
Required By    : None
Optional For   : None
Conflicts With : None
Replaces       : None
Installed Size :   3.85 MiB
Packager       : Unknown Packager
Build Date     : Mon Mar 2 20:12:25 2015
Install Date   : Mon Mar 2 20:12:54 2015
Install Reason : Explicitly installed
Install Script : Yes
Validated By   : None
[Hyperion]/home/reventlov/searx-git# searx-run                                                                                                                                                                 2015-03-02 20:15:07
Traceback (most recent call last):
  File "/usr/bin/searx-run", line 9, in <module>
    load_entry_point('searx==0.7.0', 'console_scripts', 'searx-run')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/searx/webapp.py", line 39, in <module>
    from searx.poolrequests import get as http_get
  File "/usr/lib/python2.7/site-packages/searx/poolrequests.py", line 48, in <module>
    http_adapters = cycle((HTTPAdapterWithConnParams(pool_connections=100), ))
  File "/usr/lib/python2.7/site-packages/searx/poolrequests.py", line 14, in __init__
    self.max_retries = requests.adapters.Retry(0, read=False)
AttributeError: 'module' object has no attribute 'Retry'
```

**Comment by asciimoo** [comment]
Maybe python2-requests package contains an older version of requests. Could you check it?
( command: `python2 -c 'import requests; print requests.__version__'`)

**Comment by ghost** [comment]
```
python2 -c 'import requests; print requests.__version__'
2.2.1
```

Thank you for the hint.
