### ISSUE TITLE
preferences 500 error

### ISSUE THREAD

**Issue by hys0star** [searx/searx#2919]
A 500 error occurs at a URL starting with "?preferences=". Below is the uwsgi log.

```
ERROR:searx.webapp:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/usr/local/searx/searx-src/searx/webapp.py", line 492, in pre_request
    preferences.parse_encoded_data(request.form['preferences'])
  File "/usr/local/searx/searx-src/searx/preferences.py", line 441, in parse_encoded_data
    for x, y in parse_qs(decoded_data).items():
  File "/usr/lib/python3.7/urllib/parse.py", line 675, in parse_qs
    max_num_fields=max_num_fields)
  File "/usr/lib/python3.7/urllib/parse.py", line 740, in parse_qsl
    value = _coerce_result(value)
  File "/usr/lib/python3.7/urllib/parse.py", line 103, in _encode_result
    return obj.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0142' in position 578: ordinal not in range(128)
```

**Comment by hys0star** [comment]
I think it overlaps with #2917
