### ISSUE TITLE
Please consider making the MySQL server port configurable.

### ISSUE THREAD

**Issue by virtadpt** [searx/searx#3117]
**Is your feature request related to a problem? Please describe.**
I am trying to configure Searx to connect to a MySQL database server running on a non-standard port (enforced by my hosting provider).  The database name, username, password, and host are all configurable, but the port can't be changed (it's 3306/tcp or nothing).

**Describe the solution you'd like**
I would like a "port" setting added to settings.yml where the MySQL server port to connect to could be specified.  I would also like support in searx/searx/engines/mysql_server.py to use a port specified in the settings.yml file (defaulting to 3306/tcp).

**Describe alternatives you've considered**
I've tried another piece of software that has an HTTP interface and can connect to a MySQL server to index and query a database (Manticore Search), but it only supports POST requests and there is no way to specify a request body for HTTP requests made by json_engine.py (per https://github.com/searx/searx/issues/3116).  I've tried using the command.py engine to run a script that makes queries of Manticore, but I haven't found any useful documentation on using the command.py engine, so I'm not sure how to turn the JSON output into what command.py can work with.

**Comment by virtadpt** [comment]
Sweet - thank you!

And, I didn't realize it would be that straightforward.

**Comment by virtadpt** [comment]
I don't think this completely works.  I updated to this commit last night and I'm getting an engine crash with this traceback:

```
Traceback (most recent call last):
  File "/home/drwho/searx/searx/search/processors/offline.py", line 29, in search   
    search_results = self._search_basic(query, params)
  File "/home/drwho/searx/searx/search/processors/offline.py", line 25, in _search_basic
    return self.engine.search(query, params)
  File "/home/drwho/searx/searx/engines/mysql_server.py", line 50, in search
    cur.execute(query_to_run, query_params)
  File "/home/drwho/searx/env/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "/home/drwho/searx/env/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 521, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1064 (42000): sphinxql: syntax error, unexpected string near ''wikileaks lies' LIMIT 20 OFFSET 0'
```

When running the entire query by hand in a mysql shell it works as expected:

```
SELECT id, title, content FROM articles WHERE match("wikileaks lies") LIMIT 20 OFFSET 0;
```

`mysql-connector-python` is installed into the venv I use for Searx.  Here is the config stanza from searx/searx/settings.yml:

```
# Required dependency: mysql-connector-python
  - name : mysql
    engine : mysql_server
    host : localhost
    database : Manticore
    port : 9306
    username : ''
    password : ''
    limit : 20
    query_str : 'SELECT id, title, content FROM articles WHERE match%(query)s'
    paging : False
    shortcut : archive
    disabled : False
```

I get the same results regardless of Searx being in debug mode.  The traceback is not larger or more helpful when `debug : True`.

Note: Manticore's MySQL port doesn't have any authentication on it.

I'm also poking around the Manticore community to see if the bug is there, but some initial searches suggest this is not (yet) the case.

Do you know offhand what part of Searx I should look in to narrow this error down?

**Comment by virtadpt** [comment]
Okay, I think I figured it out: This query works (though it returns raw HTML stored in the database and not the text, that's the next thing to figure out):

```
SELECT id, title, content FROM articles WHERE MATCH(%(query)s)
```
