### ISSUE TITLE
If MySQL restarts, the MySQL engine fails

### ISSUE THREAD

**Issue by virtadpt** [searx/searx#3148]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

commit 33f3f716784157a7325fba73b1c36bc175ddaa49

Not forked.

**How did you install Searx?**

Manual installation, running as a uwsgi service.

**What happened?**

I ran a search on a MySQL service configured for Searx this morning and got an error message that the search source was unavailable.  Manual examination showed that the search service was running and responding to queries executed from the context of `/usr/bin/mysql -h0 --port 9306`.

I then restarted Searx and re-ran the search, and started getting results as expected.

**How To Reproduce**

* Configure a MySQL server as a search engine to query with the mysql_engine.py service.
* Run a search to confirm that it works.
* Restart the MySQL server.
* Run the search again while watching the Searx logs.  You should get a similar exception from mysql_engine.py.
* Restart Searx.
* Run the search again.  You should get search results.

**Expected behavior**

You should get search results from the MySQL search source.

**Screenshots & Logs**

```
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]: ERROR:searx.search.processor.offline:engine mysql : exception : MySQL Connection not available.
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]: Traceback (most recent call last):
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:   File "/home/drwho/searx/searx/search/processors/offline.py", line 29, in search
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:     search_results = self._search_basic(query, params)
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:   File "/home/drwho/searx/searx/search/processors/offline.py", line 25, in _search_basic
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:     return self.engine.search(query, params)
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:   File "/home/drwho/searx/searx/engines/mysql_server.py", line 49, in search
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:     with _connection.cursor() as cur:
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:   File "/home/drwho/searx/env/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 571, in cursor
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]:     raise errors.OperationalError("MySQL Connection not available.")
Jan 22 11:45:22 exocortex.virtadpt.net searx.sh[898490]: mysql.connector.errors.OperationalError: MySQL Connection not available.
```

**Additional context**

MySQL search source is a Manticore searchd running on the same host.

Manticore's search index is rebuilt nightly.  This includes a SIGHUP to rotate the index database.

If the search index is not rebuilt nightly (i.e., no SIGHUP received), this does not happen.

This applies to "actual" MySQL servers as well.  During times when the MySQL server is briefly unavailable (hosting provider managed MySQL instance, restarted as part of regular maintenance on their part) this happens.

**Comment by virtadpt** [comment]
![mysql_engine_error](https://user-images.githubusercontent.com/639730/150654024-b525c9f9-393e-4be0-862d-0419d01d67dc.png)

**Comment by virtadpt** [comment]
Has anybody else run into this problem?
