### ISSUE TITLE
Error! Engines cannot retrieve results.  google ( Suspended: HTTP connection error )

### ISSUE THREAD

**Issue by Manifoldme** [searx/searx#3245]
**How did you install Searx?**

By using official wiki

**Do you want us (SearX dev) to give you an advice to use foreign instance from searx.space?**

Please, don't do it again, thanks.

**What happened?**

Error! Engines cannot retrieve results.

google ( [Suspended: HTTP connection error](http://192.168.50.50:8888/stats?engine=google) )

2022-06-02 12:12:27,031 WARNING:searx.engines.google: ErrorContext('searx/search/processors/online.py', 96, "response = req(params['url'], **request_args)", 'httpx.ConnectError', None, (None, None, 'www.google.com')) False
2022-06-02 12:12:27,031 ERROR:searx.engines.google: requests exception (search duration : 0.16982140857726336 s, timeout: 3.0 s) : All connection attempts failed
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:

Traceback (most recent call last):
  File "/usr/local/searx/searx-pyenv/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/local/searx/searx-pyenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by unixfox** [comment]
Please stop creating new issues, we have a dedicated section in the discussions for the installation errors: https://github.com/searx/searx/discussions/categories/installation-issue-official-wiki

I replied to your previous issue here: https://github.com/searx/searx/discussions/3244#discussioncomment-2870879

**Comment by Manifoldme** [comment]
> Please stop creating new issues, we have a dedicated section in the discussions for the installation errors: https://github.com/searx/searx/discussions/categories/installation-issue-official-wiki
> 
> I replied to your previous issue here: [#3244 (reply in thread)](https://github.com/searx/searx/discussions/3244#discussioncomment-2870879)

Sorry, I thought closed threads will be not read anymore.
