### ISSUE TITLE
enabling ccengine breaks v1.1.0

### ISSUE THREAD

**Issue by qaristote** [searx/searx#3420]
I updated my Searx instance to v1.1.0 and it fails (the uwsgi service is active but trying the website says `Internal server error`) with the following trace:
```
Nov 29 18:32:58 hermes uwsgi[377]: spawned uWSGI http 1 (pid: 464)
Nov 29 18:33:00 hermes uwsgi[411]: Traceback (most recent call last):
Nov 29 18:33:00 hermes uwsgi[411]:   File "/nix/store/g4w2jvx51k10pxlz359rszlnl99gw921-python3-3.10.8-env/lib/python3.10/site-packages/searx/webapp.py", line 142, in <module>
Nov 29 18:33:00 hermes uwsgi[411]:     search_initialize(enable_checker=True)
Nov 29 18:33:00 hermes uwsgi[411]:   File "/nix/store/g4w2jvx51k10pxlz359rszlnl99gw921-python3-3.10.8-env/lib/python3.10/site-packages/searx/search/__init__.py", line 52, in initialize
Nov 29 18:33:00 hermes uwsgi[411]:     initialize_processors(settings_engines)
Nov 29 18:33:00 hermes uwsgi[411]:   File "/nix/store/g4w2jvx51k10pxlz359rszlnl99gw921-python3-3.10.8-env/lib/python3.10/site-packages/searx/search/processors/__init__.py", line 35, in initialize
Nov 29 18:33:00 hermes uwsgi[411]:     engines.initialize_engines(engine_list)
Nov 29 18:33:00 hermes uwsgi[411]:   File "/nix/store/g4w2jvx51k10pxlz359rszlnl99gw921-python3-3.10.8-env/lib/python3.10/site-packages/searx/engines/__init__.py", line 291, in initialize_engines
Nov 29 18:33:00 hermes uwsgi[411]:     load_engines(engine_list)
Nov 29 18:33:00 hermes uwsgi[411]:   File "/nix/store/g4w2jvx51k10pxlz359rszlnl99gw921-python3-3.10.8-env/lib/python3.10/site-packages/searx/engines/__init__.py", line 284, in load_engines
Nov 29 18:33:00 hermes uwsgi[411]:     engine = load_engine(engine_data)
Nov 29 18:33:00 hermes uwsgi[411]:   File "/nix/store/g4w2jvx51k10pxlz359rszlnl99gw921-python3-3.10.8-env/lib/python3.10/site-packages/searx/engines/__init__.py", line 73, in load_engine
Nov 29 18:33:00 hermes uwsgi[411]:     engine_module = engine_data['engine']
Nov 29 18:33:00 hermes uwsgi[411]: KeyError: 'engine'
Nov 29 18:33:00 hermes uwsgi[411]: unable to load app 0 (mountpoint='') (callable not found or import error)
Nov 29 18:33:00 hermes uwsgi[411]: *** no app loaded. going in full dynamic mode ***
Nov 29 18:33:00 hermes uwsgi[375]: Tue Nov 29 18:33:00 2022 - [emperor] vassal searx.json is ready to accept requests
Nov 29 18:33:12 hermes uwsgi[411]: --- no python application found, check your startup logs for errors ---
```
After some tests it seems the root cause is ccengine: I have it enabled but removing the corresponding configuration line fixes the problem. Switching back to v1.0.0 also fixes the problem.

**Comment by unixfox** [comment]
ccengine name is now openverse, see https://github.com/searx/searx/commit/f00d9e0ec4b307fb62bd5effc7458fcfdda8fda5
