### ISSUE TITLE
Head: Crash on webapps.py line 53

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#398]
With actual head 7c9f931baff35e8a8986810971fa1949f18c19ad my system crashs on startup: 

   Traceback (most recent call last):
      File "/usr/share/searx/searx/webapp.py", line 53, in <module>
        from searx.engines import (
      File "/usr/share/searx/searx/engines/**init**.py", line 212, in <module>
        engine = load_engine(engine_data)
      File "/usr/share/searx/searx/engines/**init**.py", line 78, in load_engine
        engine.timeout = settings['outgoing']['request_timeout']
    KeyError: 'outgoing'
    Mon Aug  3 16:58:06 2015 - unable to load app 0 (mountpoint='') (callable not found or import error)

something wrong with my setup?

**Comment by cy8aer** [comment]
hm, reading helps. I junked up my settings.yml...

**Comment by cy8aer** [comment]
I did not change my settings.yml the right way, sorry
