### ISSUE TITLE
Are there any restrictions to use searx.me on mobile devices?

### ISSUE THREAD

**Issue by icaroperseo** [searx/searx#414]
Good day!

I can not use _searx.me_ on my mobile device (Android), whenever I try to access to it I get a cute **Internal Server Error**. This occurs regardless of the web browser I have installed (Firefox, Opera, Chrome). Requesting mobile or desktop version of the site in question does not solve anything.

I have come to this conclusion because if I type _searx.me/about_ shows me this page, but if I try to access a different page the indicated error arises again.

Anyone else happens the same or is an isolated case?

Thanks in advance!

**Comment by pointhi** [comment]
Try some sites listed on: http://stats.searx.oe5tpo.com. Probably we can figure out the problem. For me, https://searx.me is working correctly.

**Comment by icaroperseo** [comment]
Thanks for responding!

Of the aforementioned list, in order of appearance, the following links I produce the same error: 1, 3, 6, 8, 9. (I tried only numbered from 1 to 10)

The following works:

https://seeks.okhin.fr/
https://searx.laquadrature.net/

It seems that the problem is related to the version of the search engine or so it seemed to me.

**Comment by pointhi** [comment]
ok, I got the error message in the uwsgi-log:

```
ERROR:searx.webapp:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/searx/searx/webapp.py", line 373, in index
    'index.html',
  File "/usr/local/searx/searx/webapp.py", line 343, in render
    '{}/{}'.format(kwargs['theme'], template_name), **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx/templates/oscar/index.html", line 1, in top-level template code
    {% extends "oscar/base.html" %}
  File "/usr/local/searx/searx/templates/oscar/base.html", line 59, in top-level template code
    {% block site_alert_warning_nojs %}
  File "/usr/local/searx/searx/templates/oscar/base.html", line 62, in block "site_alert_warning_nojs"
    {% include 'oscar/messages/js_disabled.html' %}
  File "/usr/local/searx/searx/templates/oscar/messages/js_disabled.html", line 3, in top-level template code
    {{ _('Please enable JavaScript to use full functionality of this site.') }}
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/jinja2/ext.py", line 132, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/jinja2/ext.py", line 141, in gettext
    return rv % variables
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/markupsafe/__init__.py", line 101, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: incomplete format
```

**Comment by asciimoo** [comment]
hmmz, @icaroperseo what is your phones/browsers default language?

**Comment by asciimoo** [comment]
got it =)
https://searx.me/?locale=es

**Comment by Cqoicebordel** [comment]
It doesn't fallback when the language is not present :/

**Comment by icaroperseo** [comment]
@asciimoo Spanish

**Comment by asciimoo** [comment]
fixed: d5931874ac8a7762c3a961f866e65a19671f9d54 m(

**Comment by Cqoicebordel** [comment]
Nice ! (and quick !)

**Comment by icaroperseo** [comment]
It's works!!!

You rox guys!
