### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by pointhi** [searx/searx#419]
Another UTF-8 Error:
https://github.com/pointhi/searx/blob/searx_oe5tpo/searx/webapp.py#L414

```
ERROR:searx.webapp:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/searx/searx/webapp.py", line 414, in index
    result['pretty_url'] = prettify_url(result['url'])
  File "/usr/local/searx/searx/utils.py", line 227, in prettify_url
    return u'{0}[...]{1}'.format(url[:35], url[-35:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
```

**Comment by asciimoo** [comment]
Seems an engine doesn't handle unicode urls. Could you reproduce the error/investigate which engine causes it?
(we should extend our tests with unicode data)

**Comment by pointhi** [comment]
sorry, but this bug is not easy to reproduce. The same query is sometime throwing an error, sometime not.

It would be easier, to convert all url's to utf8 before doing further operations.

**Comment by asciimoo** [comment]
hopefully reproduced with the search term `한국어 위키백과에 오신 것을 환영합니다`, @pointhi could you verify the fix?

**Comment by pointhi** [comment]
seems fixed.

Now we have to update/add translations and then we should be ready for release.
