### ISSUE TITLE
Search doesn't work when using google engines in France

### ISSUE THREAD

**Issue by kujiu** [searx/searx#472]
Google shows a popup about privacy in France. Each request is rewritten by their servers and the following error occurs on searx 0.8.0:

``` python-traceback
ERROR:searx.webapp:Exception on / [GET]
Traceback (most recent call last):
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/searx/webapp.py", line 382, in index
    search.search(request)
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/searx/search.py", line 497, in search
    engine.request(self.query.encode('utf-8'), request_params)
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/searx/engines/google.py", line 201, in request
    params['cookies']['PREF'] = get_google_pref_cookie()
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/searx/engines/google.py", line 138, in get_google_pref_cookie
    pref_cookie = resp.cookies["PREF"]
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/requests/cookies.py", line 287, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/www/virtualenvs/searx/lib/python2.7/site-packages/requests/cookies.py", line 345, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='PREF', domain=None, path=None"
```

**Comment by asciimoo** [comment]
@kujiu try the latest version

**Comment by kujiu** [comment]
It's working fine with 0.8.1. Thanks for all.
