### ISSUE TITLE
duckduckgo crash and timed out, searx version is 0.8.1

### ISSUE THREAD

**Issue by phaleon2** [searx/searx#475]
ERROR:searx.search:engine crash: duckduckgo
Traceback (most recent call last):
  File "./searx/search.py", line 38, in search_request_wrapper
    return fn(url, *_kwargs)
  File "./searx/poolrequests.py", line 82, in get
    return request('get', url, *_kwargs)
  File "./searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/var/www/searx/searx-ve/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/var/www/searx/searx-ve/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/var/www/searx/searx-ve/lib/python2.7/site-packages/requests/adapters.py", line 432, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='duckduckgo.com', port=443): Max retries exceeded with url: /html?q=toto&kl=en-us&s=0 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2c6d7f80d50>, 'Connection to duckduckgo.com timed out. (connect timeout=2.0)'))

**Comment by asciimoo** [comment]
Yes, ddg is really slow.
The default timeout is 2 seconds, ddg often exceeds it, but you can set a higher timeout value in settings.yml if you have an own instance

**Comment by phaleon2** [comment]
I decided to to set a higher timeout  ( 8 seconds ) and I disabled duckduckgo in setting.yml in my own instance for now.
