### ISSUE TITLE
No results using google

### ISSUE THREAD

**Issue by rototom** [searx/searx#561]
I still get no results using google as service.
I tried to apply the patch #489  but the problem still exists.

**Comment by ammarnajjar** [comment]
An observation: I don't have that issue on my own hosted searx, also searx.me works fine, meanwhile https://search.klein-hitpass.net/ currently has that issue only when you choose to search in "General" (Allgemin) search.

**Comment by rototom** [comment]
`DEBUG:requests.packages.urllib3.connectionpool:"GET /search?q=test&start=0&gws_rd=cr&gbv=1&lr=lang_de&ei=x HTTP/1.1" 302 411
DEBUG:searx.search:google redirect on: <Response [302]>
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (31): ipv4.google.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /sorry/IndexRedirect?continue=https://www.google.de/search%3Fq%3Dtest%26start%3D0%26gws_rd%3Dcr%26gbv%3D1%26lr%3Dlang_de%26ei%3Dx&q=CGMSBAXmk9gYxIb9uQUiGQDxp4NL7jwCFAxC-NqkYPQbyffrQiXKuxA HTTP/1.1" 503 3267
ERROR:searx.search:engine crash: google
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 40, in search_request_wrapper
    ret = fn(url, *_kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 82, in get
    return request('get', url, *_kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
    *_adapter_kwargs
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 582, in send
    r = dispatch_hook('response', hooks, r, *_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/searx/searx/search.py", line 117, in process_callback
    search_results = callback(response)
  File "/usr/local/searx/searx/engines/google.py", line 198, in response
    raise RuntimeWarning('sorry.google.com')
RuntimeWarning: sorry.google.com
[pid: 976|app: 0|req: 336/336] 62.143.100.198 () {44 vars in 956 bytes} [Fri May 20 19:03:00 2016] POST / => generated 13664 bytes in 541 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 976|app: 0|req: 337/337] 62.143.100.198 () {44 vars in 956 bytes} [Fri May 20 19:03:24 2016] POST / => generated 13664 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 82 bytes (2 switches on core 0)

`

**Comment by dalf** [comment]
According to this line : 
`GET /sorry/IndexRedirect....`
google is sending a captcha.

**Comment by rototom** [comment]
Ok, but why, and how can I deal with it?

**Comment by rototom** [comment]
Ok, when I try to search using google directly on my server (using lynx) I get a message from google, that my ip address is beeing blocked because of a high amount of requests.
So google suspects me to be a robot (what is not exactly untrue, is it?)

**Comment by ibrokemypie** [comment]
has any workaround been made yet?

**Comment by asciimoo** [comment]
@rototom i don't know what can cause the constant blocking. Do you use scripts to fetch large amount of results or do you have custom settings?
