### ISSUE TITLE
DuckDuckGo Broken?

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#576]
`May 31 06:21:33 searx python2[120]: WARNING:searx.search:engine timeout: ddg definitions
May 31 06:21:33 searx python2[120]: WARNING:searx.search:engine timeout: duckduckgo
May 31 06:21:33 searx python2[120]: ERROR:searx.search:engine crash: ddg definitions
May 31 06:21:33 searx python2[120]: Traceback (most recent call last):
May 31 06:21:33 searx python2[120]: File "/root/searx/searx/search.py", line 58, in send_request
May 31 06:21:33 searx python2[120]: response = req(request_params['url'], **request_args)
May 31 06:21:33 searx python2[120]: File "/root/searx/searx/poolrequests.py", line 86, in get
May 31 06:21:33 searx python2[120]: return request('get', url, **kwargs)
May 31 06:21:33 searx python2[120]: File "/root/searx/searx/poolrequests.py", line 79, in request
May 31 06:21:33 searx python2[120]: response = session.request(method=method, url=url, **kwargs)
May 31 06:21:33 searx python2[120]: File "/usr/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
May 31 06:21:33 searx python2[120]: resp = self.send(prep, **send_kwargs)
May 31 06:21:33 searx python2[120]: File "/usr/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 576, in send
May 31 06:21:33 searx python2[120]: r = adapter.send(request, **kwargs)
May 31 06:21:33 searx python2[120]: File "/usr/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/adapters.py", line 432, in send
May 31 06:21:33 searx python2[120]: raise ConnectTimeout(e, request=request)
May 31 06:21:33 searx python2[120]: ConnectTimeout: HTTPSConnectionPool(host='api.duckduckgo.com', port=443): Max retries exceeded with url: /?q=MercedesBenz+GL%D0%9A%D0%BB%D0%B0%D1%81%D1%81++qutoru&format=json&pretty=0&no_redirect=1&d=1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fae6032ad90>, 'Connection to api.duckduckgo.com timed out. (connect timeout=3.0)'))`

Cant lynx or curl duckduckgo.com either, perhaps theyve blocked me?

**Comment by ibrokemypie** [comment]
#520 not necassarily an issue with searx, appears as if the instance is just being blocked by ddg
