### ISSUE TITLE
crashing when sites block

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#585]
numerous sites appear to be blocking searx.space now, including soundcloud.com. after updating to the latest commit and restarting, i found that searx simply would not run. debug mode shows `INFO:searx:Initialisation done
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): soundcloud.com
Traceback (most recent call last):
  File "searx/webapp.py", line 55, in <module>
    from searx.engines import (
  File "/root/searx/searx/engines/__init__.py", line 208, in <module>
    engine = load_engine(engine_data)
  File "/root/searx/searx/engines/__init__.py", line 60, in load_engine
    engine = load_module(engine_name + '.py')
  File "/root/searx/searx/engines/__init__.py", line 53, in load_module
    module = load_source(modname, filepath)
  File "/root/searx/searx/engines/soundcloud.py", line 61, in <module>
    guest_client_id = get_client_id()
  File "/root/searx/searx/engines/soundcloud.py", line 41, in get_client_id
    response = http_get("https://soundcloud.com")
  File "/root/searx/searx/poolrequests.py", line 86, in get
    return request('get', url, **kwargs)
  File "/root/searx/searx/poolrequests.py", line 79, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='soundcloud.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x30c5fd0>: Failed to establish a new connection: [Errno 110] Connection timed out',))` which has lead me to believe that due to the block by soundcloud, searx is crashing.

**Comment by dalf** [comment]
The problem occurs at this line : 
https://github.com/asciimoo/searx/blob/master/searx/engines/soundcloud.py#L61

The call is from this line : 
https://github.com/asciimoo/searx/blob/master/searx/engines/__init__.py#L53

Basically a try / catch should be used each time a engine module is loaded.

**Comment by asciimoo** [comment]
The only question is how to handle these crashes. It happens in the engine initialization phase, so we can exit/retry/skip.
