### ISSUE TITLE
socket.error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by upskaling** [searx/searx#651]
ceci est renvoyé de temps en temps pour différents clients.

```
Traceback (most recent call last):
  File "searx/webapp.py", line 769, in <module>
    run()
  File "searx/webapp.py", line 723, in run
    host=settings['server']['bind_address']
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simn
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe
```

**Comment by ibrokemypie** [comment]
```
Aug 14 20:28:31 searx python[16133]: return self.run_wsgi()
Aug 14 20:28:31 searx python[16133]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
Aug 14 20:28:31 searx python[16133]: execute(self.server.app)
Aug 14 20:28:31 searx python[16133]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
Aug 14 20:28:31 searx python[16133]: write(data)
Aug 14 20:28:31 searx python[16133]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 152, in write
Aug 14 20:28:31 searx python[16133]: self.send_header(key, value)
Aug 14 20:28:31 searx python[16133]: File "/usr/lib64/python2.7/BaseHTTPServer.py", line 401, in send_header
Aug 14 20:28:31 searx python[16133]: self.wfile.write("%s: %s\r\n" % (keyword, value))
Aug 14 20:28:31 searx python[16133]: IOError: [Errno 32] Broken pipe
```

+1 crashes very frequently

**Comment by dalf** [comment]
Do you auto complete feature enabled? If you type and quickly press enter, the response from the auto complete engine doesn't reach tbe browser (the browser closes the connection). In this scenario, you see this kind of error.

**Comment by ibrokemypie** [comment]
I have had it enabled for a while, only started occurring after pulling the latest changes
[edit] @dalf removed autcomplete, still crashes 
`Aug 25 19:14:54 searx python[3711]: return self.run_wsgi()
Aug 25 19:14:54 searx python[3711]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
Aug 25 19:14:54 searx python[3711]: execute(self.server.app)
Aug 25 19:14:54 searx python[3711]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
Aug 25 19:14:54 searx python[3711]: write(data)
Aug 25 19:14:54 searx python[3711]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 152, in write
Aug 25 19:14:54 searx python[3711]: self.send_header(key, value)
Aug 25 19:14:54 searx python[3711]: File "/usr/lib64/python2.7/BaseHTTPServer.py", line 401, in send_header
Aug 25 19:14:54 searx python[3711]: self.wfile.write("%s: %s\r\n" % (keyword, value))
Aug 25 19:14:54 searx python[3711]: IOError: [Errno 32] Broken pipe`
