### ISSUE TITLE
0.10.0 - ERROR:searx.search:engine crash: google

### ISSUE THREAD

**Issue by nevtag** [searx/searx#689]
```
ERROR:searx.search:engine crash: google
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 41, in search_request_wrapper
    ret = fn(url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 86, in get
    return request('get', url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 79, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 591, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/searx/searx/search.py", line 119, in process_callback
    search_results = callback(response)
  File "/usr/local/searx/searx/engines/google.py", line 206, in response
    raise RuntimeWarning('sorry.google.com')
RuntimeWarning: sorry.google.com
```

Same error in 0.9 version.

**Comment by dalf** [comment]
Google throws a captcha (That's the meaning of the of the RuntimeWarning sorry.google.com). 
Except changing your IP, there is no way to avoid the captcha if Google considers that your IP is abusing the service (or perhaps change the Google engine implementation, )

**Comment by nevtag** [comment]
I have made some tests, on my gateway at home, ubuntu 16.04.1 LTS, the error did not occur.
On my virtual root server  the error occur. Same ubuntu version after upgrade, heavy work with change from php5 to php7.
I will setup a proxy on my root server and will search about it over google to see if I got a captcha.

**Comment by nevtag** [comment]
That's right, google throws a captcha.
But! If you have the chance that you can use a browser on that machine and google has asked you 5 or 6 times with the captcha, than it worked with searx.
Seams so, that the ip removed from the list.

**Comment by dalf** [comment]
Interesting note ! Thanks.
