### ISSUE TITLE
download results produces error 500 "invalid html"

### ISSUE THREAD

**Issue by kkaiser** [searx/searx#924]
Hi,

I came across some queries that show results just fine on the HTML page but downloading as JSON/CSV/RSS fails with a 500 internal server error. 

- query: `(Fri Apr 22, 2016 7:30PM) (Ailey Citigroup Theater) (New York) event`
- page: 2
- engine: bing

```
GET /searx/?time_range=&q=%222016-02-16%22+%22Metropolitan+Museum+of+Art%22+New+York&pageno=2&format=json&language=en&engines=bing&category_general=1 => generated 6061 bytes in 292 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)
[2017-05-17 16:06:56,295] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/searx/searx/webapp.py", line 488, in index
    result['content'] = html_to_text(result['content']).strip()
  File "/usr/local/searx/searx/utils.py", line 131, in html_to_text
    s.feed(html)
  File "/usr/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/HTMLParser.py", line 163, in goahead
    k = self.parse_endtag(i)
  File "/usr/lib/python2.7/HTMLParser.py", line 401, in parse_endtag
    self.handle_endtag(elem)
  File "/usr/local/searx/searx/utils.py", line 95, in handle_endtag
    raise Exception("invalid html")
Exception: invalid html
```

Two more cases where this happens

- query: `(Fri Apr 01, 2016 6:00PM) (760 Rooftop @ The Copacabana Club) (New York) event`
- page: 2
- engine: google

---
- query:  `"2016-02-16" "Metropolitan Museum of Art" New York`
- page: 2
- engine: google

I could reproduce this on another instance too:
https://searx.me/?time_range=&q=(Fri+Apr+01%2C+2016+6%3A00PM)+(760+Rooftop+%40+The+Copacabana+Club)+(New+York)+event&pageno=2&format=json&language=en&engines=google&category_general=1

**Comment by Pofilo** [comment]
Problem seems to be solved. Feel free to open again if it's not !
