### ISSUE TITLE
Import error searx 0.12 at launch

### ISSUE THREAD

**Issue by Eliesemoule** [searx/searx#962]
Hello,

When I launch searx with this command : `python searx/webapp.py`, I got this error :

`Traceback (most recent call last):
  File "searx/searx/webapp.py", line 33, in <module>
    from searx import logger
  File "/usr/local/searx/searx/__init__.py", line 18, in <module>
    import certifi
ImportError: No module named certifi`

Searx was installed on CentOS 7 with the procedure in the wiki. The 0.11 of searx worked fine on my server

**Comment by Eliesemoule** [comment]
Issue solved and install procedure updated to work on CentOS 7
