### ISSUE TITLE
[bug] BASE engine encoding error

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#964]
in https://github.com/asciimoo/searx/blob/master/searx/engines/base.py
`search_results = etree.XML(resp.text)` should be replaced.

Traceback :

>ERROR:searx.search:engine base : exception : Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
Traceback (most recent call last):
  File "/home/u/abc/searx/searx/search.py", line 117, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params, start_time, timeout_limit)
  File "/home/u/abc/searx/searx/search.py", line 109, in search_one_request
    return engine.response(response)
  File "/home/u/abc/searx/searx/engines/base.py", line 77, in response
    search_results = etree.XML(resp.text, parser)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:77490)
  File "src/lxml/parser.pxi", line 1825, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116615)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

**Comment by Pofilo** [comment]
Can you reopen providing more information if you think the problem is still relevant ?
